#pragma once

constexpr long DMX_CHANNELS = 512;
constexpr long DMX_FIRST_CLOCK_CHANNEL = 506;
constexpr long NUM_CLOCK_CHANNELS = 7;

constexpr bool RUN_TESTS_ON_STARTUP = false;

constexpr long MOTOR1_PUL = 5;
constexpr long MOTOR2_PUL = 6;
constexpr long MOTORS_ENABLE = 8;
constexpr long MOTOR1_DIR = 10;
constexpr long MOTOR2_DIR = 11;

constexpr long DMX_LED_PIN = 7;

constexpr long MAX_INT = (~0u)/2;

constexpr long STEPS_PER_REVOLUTION = 400;
constexpr long HOUR_HAND_MICROSTEPS = 8;
constexpr long MINUTE_HAND_MICROSTEPS = 8;
constexpr long HOUR_HAND_MICROSTEPS_PER_REVOLUTION = STEPS_PER_REVOLUTION * HOUR_HAND_MICROSTEPS;
constexpr long MINUTE_HAND_MICROSTEPS_PER_REVOLUTION = STEPS_PER_REVOLUTION * MINUTE_HAND_MICROSTEPS;

constexpr float MAX_SPEED_STEPS_PER_SECOND = 300.0f;
constexpr float REALTIME_SPEED_STEPS_PER_SECOND = (float)STEPS_PER_REVOLUTION / 60 / 60;
constexpr long HOUR_HAND_MAX_SPEED = MAX_SPEED_STEPS_PER_SECOND * HOUR_HAND_MICROSTEPS;
constexpr long MINUTE_HAND_MAX_SPEED = MAX_SPEED_STEPS_PER_SECOND * MINUTE_HAND_MICROSTEPS;

constexpr long NUM_POSITIONS = 240;